version: "2"         # required to adjust maintainability checks
checks:
  method-complexity:
    config:
      threshold: 10

plugins:
  rubocop:
    enabled: true
    config:
      file: .rubocop.yml
